# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8418fcea98a874964fcf38d358c00ab18abfff0003737090f4257bf2d51e6ad7477097844e231d5d668c96e6208aaae4c5336cc1cda2d7dd44292c27fec25ca9

test:
  secret_key_base: 00027e9c742491e8e63fcdc58703755eef982d688fb4157e865e2837563a6e6ad70252bdc770bf624a2fe1279e2fa506af10b3da152eaef95fe98b255f143a6c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
